#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds the data files the reader app (index.html / app.js) needs, from the 604 page files in
Pages/ and the shared JSON data in ../source_data. build_pages.py runs this after writing the pages;
run it on its own only if the JSON data changed:

    python viewer/build_app_data.py

Writes (as plain JS so the app works without a JSON fetch):
  data/app_index.js  - pages (ayahs on each page, juz, hizb), surahs (name, start page), juz start pages
  data/quran_text.js - ayah text and the theme of each ayah, used by the ayah panel
"""

import hashlib
import json
import os
import re
import sys

HTML_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE_DATA = os.path.join(os.path.dirname(HTML_DIR), 'source_data')
PAGES_DIR = os.path.join(HTML_DIR, 'Pages')
OUT_DIR = os.path.join(HTML_DIR, 'data')
TOTAL_PAGES = 604

POLY = re.compile(r'<path class="ayahPolygon"[^>]*?ayah="(\d+)" surah="(\d+)"')


def load(name):
    with open(os.path.join(SOURCE_DATA, name), encoding='utf-8') as f:
        return json.load(f)


def main():
    sys.stdout.reconfigure(encoding='utf-8')
    text = load('quran-full-tashkeel.json')
    complete = load('quran_complete.json')
    divisions = load('quran_divisions_map.json')

    # Ayahs on each page, in reading order, taken from the page files themselves.
    pages = []
    digest = hashlib.sha1()     # pages version: installed apps drop their stored pages when it changes
    for p in range(1, TOTAL_PAGES + 1):
        with open(os.path.join(PAGES_DIR, f'{p:03d}.html'), 'rb') as f:
            raw = f.read()
        digest.update(raw)
        html = raw.decode('utf-8')
        seen, ayahs = set(), []
        for a, s in POLY.findall(html):
            key = (int(s), int(a))
            if key not in seen:
                seen.add(key)
                ayahs.append(key)
        if not ayahs:
            raise SystemExit(f'Page {p}: no ayahPolygon found')
        first, last = ayahs[0], ayahs[-1]
        d = [divisions.get(f'{s}:{a}', {}) for s, a in ayahs]
        pages.append({
            'first': list(first), 'last': list(last),
            'surahs': sorted({s for s, _ in ayahs}),
            # A juz or quarter that starts on this page wins over the one continuing from the page before.
            'juz': d[-1].get('juz', 1),
            'hq': d[-1].get('hizb_quarter', 1),
            'juzs': sorted({x.get('juz', 1) for x in d}),
        })

    # Cross-check against the division map's own page numbers.
    mismatches = 0
    for p, info in enumerate(pages, 1):
        d = divisions.get(f"{info['first'][0]}:{info['first'][1]}", {})
        if d.get('page') not in (None, p):
            mismatches += 1
    print(f'pages: {len(pages)}, first-ayah page mismatches vs divisions map: {mismatches}')

    start_page = {}
    for p, info in enumerate(pages, 1):
        for s in info['surahs']:
            start_page.setdefault(s, p)

    surahs = [{
        'id': s['id'], 'name': s['name'], 'tr': s['transliteration'],
        'type': s['type'], 'verses': s['total_verses'], 'page': start_page[s['id']],
    } for s in text]

    juz_start = {}
    for p, info in enumerate(pages, 1):
        for j in info.pop('juzs'):
            juz_start.setdefault(j, p)
    juz = [juz_start[j] for j in range(1, 31)]

    # Themes: one entry per (surah, ayah range).
    themes = []
    for s in complete['surahs']:
        for sec in s['sections']:
            if sec.get('theme'):
                themes.append([s['surah_id'], sec['ayah_start'], sec['ayah_end'], sec['theme']])

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, 'app_index.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by build_app_data.py - do not edit by hand.\n')
        f.write('window.QURAN_INDEX = ')
        json.dump({'pagesVersion': digest.hexdigest()[:12], 'pages': pages, 'surahs': surahs, 'juz': juz},
                  f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    with open(os.path.join(OUT_DIR, 'quran_text.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by build_app_data.py - do not edit by hand.\n')
        f.write('window.QURAN_TEXT = ')
        json.dump([[v['text'] for v in s['verses']] for s in text], f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\nwindow.QURAN_THEMES = ')
        json.dump(themes, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    print(f'surahs: {len(surahs)}, juz starts: {juz}, themes: {len(themes)}, pages version: {digest.hexdigest()[:12]}')


if __name__ == '__main__':
    main()
